from pathlib import Path
p=Path('/vol1/@appcenter/vehicle-mgr/后端/后台管理/index.html')
s=p.read_text(encoding='utf-8')
over=r'''

// ===== 合同配件模板导入：车型、配件名称、配件价格、工时费、合计金额 =====
function downloadContractTemplate(){
  fetch(B+'/api/contract-parts/template.xlsx',{headers:{'Authorization':'Bearer '+T}}).then(function(r){if(!r.ok)throw new Error('下载模板失败');return r.blob()}).then(function(b){var a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='合同配件导入模板.xlsx';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}).catch(function(e){toast('失败: '+e.message,1)})
}
function page_contract(el){
  el.innerHTML='<div class="page-title">📦 合同配件明细</div>'+ 
    '<div class="card"><div class="filter-bar"><div class="form-group"><label>搜索配件</label><input id="cpq" placeholder="配件名称" /></div><button class="btn btn-primary" onclick="loadContractParts()">查询</button><button class="btn btn-primary" onclick="showContractPartForm()">+ 添加配件</button><button class="btn btn-secondary" onclick="downloadContractTemplate()">下载模板</button><button class="btn btn-secondary" onclick="showContractImport()">按模板导入</button></div><p style="color:#888;font-size:12px;margin-top:10px;">模板最低必填：车型、配件名称、配件价格、工时费、合计金额。可选：修理厂ID、配件型号、质保天数、备注。</p></div>'+ 
    '<div class="card" id="cpw"><p class="loading">加载中...</p></div>';
  loadContractParts();
}
function loadContractParts(){var q=document.getElementById('cpq')?document.getElementById('cpq').value:'';api('GET','/api/contract-parts'+(q?'?q='+encodeURIComponent(q):'')).then(function(items){var h='<table><tr><th>ID</th><th>修理厂ID</th><th>车型</th><th>配件名称</th><th>型号</th><th>配件价格</th><th>工时费</th><th>合计金额</th><th>质保天数</th><th>备注</th><th>操作</th></tr>';for(var i=0;i<items.length;i++){var x=items[i];h+='<tr><td>'+x.id+'</td><td>'+(x.shop_id||'')+'</td><td>'+esc(x.vehicle_model||'')+'</td><td>'+esc(x.part_name)+'</td><td>'+esc(x.part_model||'')+'</td><td>'+(x.contract_price||0)+'</td><td>'+(x.labor_fee||0)+'</td><td>'+(x.total_amount||0)+'</td><td>'+(x.warranty_days||0)+'</td><td>'+esc(x.notes||'')+'</td><td><button class="btn btn-sm btn-secondary" onclick="showContractPartForm('+x.id+')">编辑</button><button class="btn btn-sm btn-danger" onclick="delContractPart('+x.id+')">删除</button></td></tr>'}h+='</table>';if(!items.length)h='<p style="text-align:center;padding:20px;color:#555;">暂无数据</p>';document.getElementById('cpw').innerHTML=h})}
function showContractPartForm(id){var load=id?api('GET','/api/contract-parts').then(function(a){return a.find(function(x){return x.id===id})||{}}):Promise.resolve({});load.then(function(x){loadShopOptions(x.shop_id,function(shops){var d=document.createElement('div');d.innerHTML='<div class="modal-overlay"><div class="modal-content"><h3>'+(id?'编辑':'添加')+'合同配件</h3><div class="form-group"><label>修理厂</label><select id="cp1">'+shops+'</select></div><div class="form-group"><label>车型 *</label><input id="cpv" value="'+esc(x.vehicle_model||'')+'" /></div><div class="form-group"><label>配件名称 *</label><input id="cp2" value="'+esc(x.part_name||'')+'" /></div><div class="form-group"><label>配件型号</label><input id="cp3" value="'+esc(x.part_model||'')+'" /></div><div class="form-group"><label>配件价格 *</label><input id="cp4" type="number" value="'+(x.contract_price||0)+'" /></div><div class="form-group"><label>工时费 *</label><input id="cp7" type="number" value="'+(x.labor_fee||0)+'" /></div><div class="form-group"><label>合计金额 *</label><input id="cp8" type="number" value="'+(x.total_amount||0)+'" /></div><div class="form-group"><label>质保天数</label><input id="cp5" type="number" value="'+(x.warranty_days||0)+'" /></div><div class="form-group"><label>备注</label><input id="cp6" value="'+esc(x.notes||'')+'" /></div><div style="text-align:right;margin-top:16px;"><button class="btn btn-secondary" onclick="clo()">取消</button><button class="btn btn-primary" onclick="saveContractPart('+(id||0)+')" style="margin-left:8px;">保存</button></div></div></div>';document.body.appendChild(d.firstElementChild)})})}
function saveContractPart(id){var shop=document.getElementById('cp1').value;var d={shop_id:shop?parseInt(shop):null,vehicle_model:document.getElementById('cpv').value.trim(),part_name:document.getElementById('cp2').value.trim(),part_model:document.getElementById('cp3').value.trim(),contract_price:parseFloat(document.getElementById('cp4').value)||0,labor_fee:parseFloat(document.getElementById('cp7').value)||0,total_amount:parseFloat(document.getElementById('cp8').value)||0,warranty_days:parseInt(document.getElementById('cp5').value)||0,notes:document.getElementById('cp6').value};if(!d.vehicle_model||!d.part_name){toast('请输入车型和配件名称',1);return}api(id?'PUT':'POST','/api/contract-parts'+(id?'/'+id:''),d).then(function(){clo();toast('保存成功');loadContractParts()}).catch(function(e){toast('失败: '+e.message,1)})}
function showContractImport(){var d=document.createElement('div');d.innerHTML='<div class="modal-overlay"><div class="modal-content"><h3>按模板导入合同配件</h3><p style="color:#888;font-size:13px;line-height:1.8;">请先下载模板，按模板填写后上传。<br/>最低必填列：车型、配件名称、配件价格、工时费、合计金额。<br/>可选列：修理厂ID、配件型号、质保天数、备注。</p><button class="btn btn-secondary" onclick="downloadContractTemplate()">下载模板</button><div class="form-group" style="margin-top:12px;"><label>选择填写后的模板文件</label><input type="file" id="cpf" accept=".xlsx,.xls" /></div><div style="text-align:right;margin-top:16px;"><button class="btn btn-secondary" onclick="clo()">取消</button><button class="btn btn-primary" onclick="doContractImport()" style="margin-left:8px;">一键导入</button></div></div></div>';document.body.appendChild(d.firstElementChild)}
function doContractImport(){var f=document.getElementById('cpf').files[0];if(!f){toast('请选择文件',1);return}var fd=new FormData();fd.append('file',f);fetch(B+'/api/contract-parts/import/xlsx',{method:'POST',headers:{'Authorization':'Bearer '+T},body:fd}).then(function(r){return r.json().then(function(j){if(!r.ok)throw new Error(j.detail||'导入失败');return j})}).then(function(x){clo();toast('导入完成：'+x.imported+'条，跳过'+x.skipped+'条');loadContractParts()}).catch(function(e){toast('失败: '+e.message,1)})}
'''
s=s.replace('\n</script>','\n'+over+'\n</script>')
p.write_text(s,encoding='utf-8')
print('contract frontend template patched')
